client_max_body_size 50m;
client_body_buffer_size 512k;

gzip_min_length 1k;
gzip_buffers 4 16k;
gzip_http_version 1.0;
gzip_comp_level 9;
gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
gzip_vary on;
gzip_disable "MSIE [1-6]\.";

log_format 77tv '[$time_local] $request_time [$remote_addr|$http_x_forwarded_for|$http_x_real_ip] ' '[$request] $status ' '[$http_referer] [$http_user_agent]';

server {
    listen      80;

    location / {
        root /opt/platform-admin-vue/;
        try_files $uri $uri/ /master-dist/index.html;
        index index.html;
    }

    location @router {
        rewrite ^.*$ /index.html last;
    }
}
